heat_template_version: 2017-09-01

resources:
  secgroup:
    type: OS::Neutron::SecurityGroup
    properties:
      name: sg_wordpress
      description: wordpress security group
      rules:
      - protocol: icmp
      - protocol: tcp
        port_range_min: 80
        port_range_max: 80
      - protocol: tcp
        port_range_min: 3306
        port_range_max: 3306
  db:
    type: OS::Zun::Container
    properties:
      image: mysql:5.7
      environment:
        MYSQL_ROOT_PASSWORD: rootpass
        MYSQL_DATABASE: wordpress
      security_groups:
      - {get_resource: secgroup}
  wordpress:
    type: OS::Zun::Container
    properties:
      image: "wordpress:latest"
      environment:
        WORDPRESS_DB_HOST: {get_attr: [db, addresses, private, 0, addr]}
        WORDPRESS_DB_USER: root
        WORDPRESS_DB_PASSWORD: rootpass
      security_groups:
      - {get_resource: secgroup}
  floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: public
  association:
    type: OS::Neutron::FloatingIPAssociation
    properties:
      floatingip_id: { get_resource: floating_ip }
      port_id: {get_attr: [wordpress, addresses, private, 0, port]}

outputs:
  url:
    value: {get_attr: [floating_ip, floating_ip_address]}
    description: The web server url
